version: "2"
services:
  rappi-app:
    build: ./rappi-app
    links:
      - rappi-mysql
    ports:
      - "5000:5000"
    environment:
      - RAPPI_DB_PORT=3306
      - RAPPI_DB_HOST=rappi-mysql
    networks:
      - default
  rappi-mysql:
    build: ./rappi-mysql
    ports:
      - "5001:3306"
    networks:
      - default
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rappi-secret
